# backend/template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LEAP-Guard 360 Inference API

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - POST
            - OPTIONS
          AllowHeaders:
            - Content-Type
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "arn:aws:bedrock:ap-southeast-1::foundation-model/anthropic.claude-haiku-4-5-20251015-v1:0"
      Environment:
        Variables:
          MOCK_BEDROCK: "false"
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  FunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt InferenceFunctionUrl.FunctionUrl
