# backend/template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LEAP-Guard 360 Inference API

Globals:
  Function:
    Timeout: 60
    MemorySize: 2048

Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - Content-Type
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - "arn:aws:bedrock:*:377133361984:inference-profile/apac.amazon.nova-micro-v1:0"
                - "arn:aws:bedrock:*::foundation-model/amazon.nova-micro-v1:0"
      Environment:
        Variables:
          MOCK_BEDROCK: "false"
      ImageUri: 377133361984.dkr.ecr.ap-southeast-1.amazonaws.com/leap-guard-inference:latest

Outputs:
  FunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt InferenceFunctionUrl.FunctionUrl
